#ifndef GITHUBACTIONSTEST_GLOBAL_H
#define GITHUBACTIONSTEST_GLOBAL_H

#if defined(GITHUBACTIONSTEST_LIBRARY)
#  define GITHUBACTIONSTEST_EXPORT Q_DECL_EXPORT
#else
#  define GITHUBACTIONSTEST_EXPORT Q_DECL_IMPORT
#endif

#endif // GITHUBACTIONSTEST_GLOBAL_H
